### ISSUE TITLE
Uso indevido

### ISSUE THREAD

**Issue by HerickRaposo** [SeuAliado/OpenCEP#1]
Boa tarde,, sou desenvolvedor da Empresa Mury Contábil em São Lourenço -MG, atualmente em nossos sistemas estamos tendo um alto fluxo de informações, sendo assim gostaria de saber quais são as boas práticas de consumo, qual o limite de consulta que posso fazer e se esse limite é dado por minutos, por hora ou diário para não tomar uso indevido e ban. Aguardo retorno!

**Comment by SeuAliado** [comment]
Olá Herick, atualmente não temos nenhum tipo de limite para a pesquisa na API do OpenCEP e isso só é possível devido a tecnologia JAMSTACK que usamos na qual colocamos toda a carga na CDN da CloudFlare, então pode usar à vontade.

Caso tenha alguma dificuldade ou tenha algum bloqueio é só abrir um issue que verificamos o que esta acontecendo.
