### ISSUE TITLE
Falha na busca do CEP 18542470 sem a extenção ".json"

### ISSUE THREAD

**Issue by lucascm** [SeuAliado/OpenCEP#14]
Inclui o arquivo ./v1/18542470.json, mas a pesquisa "https://opencep.com/v1/18542470" continua retornando erro 404.

Se pesquisar https://opencep.com/v1/18542470.json, retorna os dados corretamente.

O que precisa ser feito para que a pesquisa sem a extensão ".json" funcione corretamente?

**Comment by lucascm** [comment]
Percebi que as pesquisas realizadas em servidores dentro do país (Brasil) retornam o erro 404. A pesquisa realizada em servidores fora do país retorna o endereço cadastrado. 

O serviço tem um CDN? É provável que não tenha atualizado os servidores locais.

**Comment by hiuryanderson** [comment]
Boa noite, exatamente isso!

Já liberei o cache para BR e agora esta funcionando!
