### ISSUE TITLE
Falha na busca do CEP 18.548-272

### ISSUE THREAD

**Issue by lucascm** [SeuAliado/OpenCEP#18]
Verifiquei que o arquivo https://github.com/SeuAliado/OpenCEP/blob/main/v1/18548272.json existe, porém ao pesquisar pela API (https://opencep.com/v1/18548272 ou https://opencep.com/v1/18548272.json), está retornando o código 404

Segue evidência

![print](https://github.com/SeuAliado/OpenCEP/assets/4426670/d6a4bbb4-92b7-4f0a-aba9-5b0e24f9d2ac)

**Comment by lucascm** [comment]
Verifiquei que a pesquisa em links que estão fora do Brasil, está retornando o endereço corretamente. A busca a partir de links no Brasil, ainda retorna o erro 404.

**Comment by hiuryanderson** [comment]
Liberei o cache para o Brasil, agora esta OK.

Libera o cache do seu navegador que deve funcionar!
