### ISSUE TITLE
Falha na busca do CEP  95680236

### ISSUE THREAD

**Issue by SkyTeam-Dev** [SeuAliado/OpenCEP#19]
Ao realizar a busca via api https://opencep.com/v1/95680236.json não é encontrado o endereço conforme abaixo.

**_https://buscacepinter.correios.com.br/app/endereco/index.php?endereco=95680236_**

**R. Ignácio Saturnino de Moraes, 427 - Centro Canela - RS, 95680-236**

**Comment by hiuryanderson** [comment]
Adicionado
