### ISSUE TITLE
Erro 404 na consulta do CEP 13650007

### ISSUE THREAD

**Issue by lucascm** [SeuAliado/OpenCEP#25]
Verifiquei que o arquivo https://github.com/SeuAliado/OpenCEP/blob/main/v1/13650007.json existe, porém ao consultar o endereço https://opencep.com/v1/13650007.json, estou recebendo o erro 404 com a seguinte mensagem:

```
{
  "error": true
}
```

**Comment by hiuryanderson** [comment]
Olá Lucas,

Realmente teve um problema na limpeza do cache. Já arrumei o problema e acredito que não acontecerá mais nos próximos!

**Comment by lucascm** [comment]
Boa tarde,

verifiquei que ainda está gerando o erro 404 para este CEP
