### ISSUE TITLE
Erro 404 na busca do CEP 37830026 no Brasil

### ISSUE THREAD

**Issue by lucascm** [SeuAliado/OpenCEP#29]
Verifiquei que o arquivo https://github.com/SeuAliado/OpenCEP/blob/main/v1/37830026.json já existe no repositório, porém ao pesquisar pelo Brasil, não está encontrando o CEP 37830026.

Ao acessar o endereço "https://opencep.com/v1/37830026", está retornando o erro abaixo, com o código 404.

{
  "error": true
}

OBS: ao pesquisar em servidores fora do Brasil, a pesquisa retorna corretamente.

**Comment by lucascm** [comment]
O problema ainda persiste

**Comment by hiuryanderson** [comment]
> O problema ainda persiste

Muito estranho, testei aqui e parece que esta funcionando. Limpa o cache do seu navegador e testa novamente, pode ser que seja o cache do navegador.
