### ISSUE TITLE
Erro CEP 17910000

### ISSUE THREAD

**Issue by DesenvolvimentoFC** [SeuAliado/OpenCEP#33]
Boa tarde, notei que na consulta do CEP 17910000, o retorno esta sendo: 

404

There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account.
[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

Buscando no site dos correios o mesmo se apresenta valido.

Logradouro/Nome | Bairro/Distrito | Localidade/UF | CEP

Rodovia Comandante João Ribeiro de Barros | Metrópole | Dracena/SP | 17910-000

**Comment by DesenvolvimentoFC** [comment]
Ola, boa tarde, notei que o cep 12122-268, nao esta sendo encontrado pela api.

Logradouro/Nome | Bairro/Distrito | Localidade/UF | CEP

Rua das Araucárias | Condomínio Colonial Vale do Sol | Tremembé/SP | 12122-268

**Comment by zerossB** [comment]
@DesenvolvimentoFC 

Faça uma contribuição ao projeto, no README dele ja comenta, se encontrar alguma coisa de errado pode contribuir com um PR.

https://github.com/SeuAliado/OpenCEP/tree/main/v1#achou-um-cep-incorreto

**Comment by SeuAliado** [comment]
Já atualizado!
