### ISSUE TITLE
CEP não disponivel

### ISSUE THREAD

**Issue by Raulourenc** [SeuAliado/OpenCEP#34]
{
  "cep": "13494-028",
  "logradouro": "Rua Renato de Freitas Levy",
  "complemento": "",
  "bairro": "Distrito Industrial e Comercial Flamínio de Freitas Levy",
  "localidade": "Cordeirópolis",
  "uf": "SP",
  "ibge": "3512407"
}

**Comment by SeuAliado** [comment]
Atualizado!
