### ISSUE TITLE
Sugestão: Velocidade de extração zip VS velocidade de clone do repo

### ISSUE THREAD

**Issue by henriquemafra** [SeuAliado/OpenCEP#35]
Primeiramente, gostaria de agradecer pelo excelente projeto compartilhado. Em segundo lugar, gostaria de compartilhar uma opinião: anteriormente, estava mais fácil obter os dados de CEP ao clonar o repositório, pois a transferência era, com certeza, muito mais veloz. A extração do release no formato ZIP está demorando demais.

**Comment by SeuAliado** [comment]
Olá Henrique,

Realmente eu gostava muito de como o projeto estava antes. Fomos obrigados a alterar a estrutura do projeto pelo Github, pois informaram que o tamanho do projeto no servidor deles estava muito grande com mais de 1 Tera após a criação de commits, branches e forks. Ou seja, não tivemos muita escolha, tivemos que limpar todo histórico, commits, branches e remover todos os forks e ainda tivemos que pagar de usar o githubpages e passamos para uma hospedagem no Google Cloud Storage para manter o projeto online.

Por enquanto a compactação em ZIP foi a melhor maneira que encontrei para manter a estrutura em arquivos estáticos e utilizável foi compactar e manter no próprio projeto.

A API ainda esta se mantendo atualizada todos os dias com novos CEPS, porém compactar os arquivos e lançar um novo release ainda não esta automático e vamos trabalhar para ajustar isso logo logo.

Se tiver alguma ideia de como podemos fazer para melhorar, podemos testar por aqui.

**Comment by henriquemafra** [comment]
Que triste, está explicado então. Mas de toda forma não deixou de ser um excelente projeto.

Por enquanto não encontrei nada que precise urgentemente de melhorias, o projeto está fantástico e é extremamente útil, para evitar problemas de ceps ausentes ou com erros, que são normais em algo dessa magnitude, eu costumo adicionar redundâncias e fazer comparações com outras APIs, caso não exista em uma talvez encontre em outra. Aliás, escrevendo isso acabei de ter uma ideia, vou adicionar uma linha no meu código para aproveitar o consumo dos meus clientes e registrar ceps ausentes ou dados inconsistentes para informar aqui.

Obrigado por todo tempo prestado em prol da comunidade, um abraço.

**Comment by SeuAliado** [comment]
Show.

Para facilitar as atualizações no projeto temos um script que faz essa atualização automática no dos ceps na api, e você pode usar para quando não encontrar o cep, mas que ele exista em algum lugar:
https://update.opencep.com/15050305

Só peço que não use ele como padrão de busca e use somente como um local para atualizar o cep, caso ele esteja desatualizado. Por ser um script que fala com vários serviços, google storage, github e cloudflare ele tende a ser lento, pois depende de várias respostas.
