### ISSUE TITLE
CEP não encontrado

### ISSUE THREAD

**Issue by CleytonX8** [SeuAliado/OpenCEP#36]
O cep do JSON abaixo não existe na api de vocês

response da rota https://viacep.com.br/ws/76964705/json/
{
  "cep": "76964-705",
  "logradouro": "Rua Macela",
  "complemento": "(Loteamento Residencial São Marcos)",
  "unidade": "",
  "bairro": "Colina Verde",
  "localidade": "Cacoal",
  "uf": "RO",
  "ibge": "1100049",
  "gia": "",
  "ddd": "69",
  "siafi": "0009"
}

response da rota https://opencep.com/v1/76964705:
{
    "error": true
}

**Comment by SeuAliado** [comment]
Atualizado no gateway:
https://opencep.com/v1/76964705

E já adicionaremos na próxima versão para baixar o pacote de CEPs
