### ISSUE TITLE
CEP 36490118

### ISSUE THREAD

**Issue by GabrielButarelo** [SeuAliado/OpenCEP#37]
O CEP 36490118 não existe na API, poderiam adicionar por favor?

https://viacep.com.br/ws/36490118/json/
{
  "cep": "36490-118",
  "logradouro": "Travessa Alfredo Fernandes Gomes",
  "complemento": "",
  "unidade": "",
  "bairro": "Centro",
  "localidade": "Ouro Branco",
  "uf": "MG",
  "ibge": "3145901",
  "gia": "",
  "ddd": "31",
  "siafi": "4917"
}

https://opencep.com/v1/36490118
{
"error": true
}

**Comment by SeuAliado** [comment]
Adicionado. Confira em:
https://opencep.com/v1/36490118

Muito Obrigado!
