### ISSUE TITLE
CEP 17480015

### ISSUE THREAD

**Issue by GabrielButarelo** [SeuAliado/OpenCEP#38]
O CEP 17480015 não existe na API, poderiam adicionar por favor?

https://viacep.com.br/ws/17480015/json/
{
  "cep": "17480-015",
  "logradouro": "Rua Antônio Consalter Longo",
  "complemento": "",
  "unidade": "",
  "bairro": "Centro",
  "localidade": "Cabrália Paulista",
  "uf": "SP",
  "estado": "São Paulo",
  "regiao": "Sudeste",
  "ibge": "3508306",
  "gia": "2320",
  "ddd": "14",
  "siafi": "6267"
}

https://opencep.com/v1/17480015
{
"error": true
}

**Comment by hiuryanderson** [comment]
Muito Obrigado!

Adicionado.
