### ISSUE TITLE
Error 401 em IP específico

### ISSUE THREAD

**Issue by arquimedesurf** [SeuAliado/OpenCEP#39]
Estou tomando o erro abaixo ao realizar requisição em um IP ESPECÍFICO:
Error [401 Unauthorized] during [GET] to [https://opencep.com/v1/65091570 ] [ViaCepService#getLogradouro(String)]: [<?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>]

Ao realizar consulta na API OPENCEP através de outro IP ocorre sucesso na resposta (200).

Esse IP ESPECÍFICO pode estar bloqueado pelo servidor/rede da API OPENCEP.COM?

**Comment by hiuryanderson** [comment]
Olá @arquimedesurf,

Não temos nenhum bloqueio de IP configurado no nosso firewall até o momento.

Usamos o Cloudflare que faz várias verificações para a validade da requisição, além também do Google Cloud storage que faz outras verificações.

Dá uma verificada que o seu código está enviando todos os dados para uma requisição válida e qualquer dúvida compare com o exemplo do POSTMAN do projeto no link abaixo:

https://app.getpostman.com/run-collection/3084518-e1c46f9e-fd0d-4cb6-8d02-0ba532273e5a?action=collection%2Ffork&collection-url=entityId%3D3084518-e1c46f9e-fd0d-4cb6-8d02-0ba532273e5a%26entityType%3Dcollection%26workspaceId%3D121752ec-9dfc-4ea6-8ad0-9e3fe06c3558

Se o erro persistir envie-nos mais detalhes de como você esta realizando a conexão que podemos verificar melhor o que se trata.
