### ISSUE TITLE
Acentos incorretos

### ISSUE THREAD

**Issue by Andre-Silva-Peixoto** [SeuAliado/OpenCEP#42]
![imagem_2024-12-02_121719651](https://github.com/user-attachments/assets/ab4ffa96-02d0-41ab-a578-af4006051e7c)

**Comment by hiuryanderson** [comment]
@Andre-Silva-Peixoto eu fiz os testes aqui e parece que esta certinho! Verifica se a requisição esta usando o Accept-Encoding correto para que a acentuação funcione corretamente!

Teste o nosso projeto no postman que já corrige automaticamente esses detalhes de requisição:
https://app.getpostman.com/run-collection/3084518-e1c46f9e-fd0d-4cb6-8d02-0ba532273e5a?action=collection%2Ffork&collection-url=entityId%3D3084518-e1c46f9e-fd0d-4cb6-8d02-0ba532273e5a%26entityType%3Dcollection%26workspaceId%3D121752ec-9dfc-4ea6-8ad0-9e3fe06c3558
