### ISSUE TITLE
Como coloco online localmente?

### ISSUE THREAD

**Issue by vcasadei** [SeuAliado/OpenCEP#44]
Baixei o release do banco de dados e o código fonte, mas na verdade não tem código fonte. Como subo localmente?

**Comment by hiuryanderson** [comment]
@vcasadei ai esta o grande segredo do formato JAMSTACK ele não é um executável são arquivos de textos estáticos que podem ser acessados direto no navegador! Isso possibilita que a api funcione muito rápido, muito estável e sem altos custos!

É só subir os arquivos estáticos com a extensão .json e acessar pelo url deles!
