### ISSUE TITLE
CEP 70864040 com dois locais diferentes

### ISSUE THREAD

**Issue by Jonasapm94** [SeuAliado/OpenCEP#45]
Um dos locais se refere a Brasília (é o correto, com base em consultas em outras apis). O outro local é a Rua Topázio Imperial em Boa Vista, RR. 
Os demais dados apresentam estarem corretos. A mudança deve ser feita apenas no cep deste último para o valor de 69310188.

**Comment by hiuryanderson** [comment]
@Jonasapm94 já atualizei, da uma checada se está correto agora:

https://update.opencep.com/69310188

Muito Obrigado pela contribução!
