### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by lipeee17** [SeuAliado/OpenCEP#7]
Excelente projeto! Estão de parabéns. 
No descrição diz CORS livre,  Mas tive problemas de CORS ao utilizar em um app usando framework Ionic + angular.
Poderiam me ajudar?
![image](https://github.com/SeuAliado/OpenCEP/assets/31443270/6fe5f005-ed28-443a-b124-35d658dbb5cd)

**Comment by hiuryanderson** [comment]
Olá Felipe,

O CORS esta setado corretamente no domínio, veja alguns sites que verificam abaixo:
https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fopencep.com%2Fv1%2F20710080&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

https://cors-test.codehappy.dev/?url=https%3A%2F%2Fopencep.com%2Fv1%2F20710080&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get

O que pode estar acontecendo é o framework ionic + angular não permirtir requisição externa, assim como o domínio de origem. Deu uma olhadinha e parece que esse problema acontece normalmente:
